name: 'analytics'
version: '0.1'

config-version: 2

profile: 'analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         
  - "target"
  - "dbt_packages"

models:
  analytics:
    raw:
      +materialized: table

tests:
  singular:
    - tests/test_invalid_email.sql
    - tests/test_product_prices_positive.sql
